spring:
  profiles:
    active: local

logging:
  level:
    io.pivotal.demo: INFO
    org.hibernate.SQL: INFO

server:
  port: ${PORT:8090}

management:
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      roles: USER
      show-details: always
    env:
      keys-to-sanitize:  pwd,uid,password,secret,key,client_id,client_key # suffix or regex

contact:
  dataservice:
    endpoint: ${vcap.services.contact-service.credentials.uri:http://localhost:8080}
    unavailable: '{"status":503,"data":"Service currently unavailable."}'

---
spring:
  profiles: local

---
spring:
  profiles: cloud
