logging:
  level:
    io.pivotal.demo: DEBUG
server:
  port: 8090

contact:
  dataservice:
    endpoint: http://${vcap.services.contact-service.credentials.uri:localhost:8080}
    unavailable: '{"status":503,"data":"Service currently unavailable."}'

---
spring:
  profiles: local
  redis:
    host: localhost
    port: 6379
    password: guest
  
---
spring:
  profiles: cloud
