---
resources:
- name: lab-repo
  type: git
  source:
    uri: git@github.com:jigsheth57/Cloud-Native-Workshop.git
    branch: master
    private_key: {{git_private_key}}

- name: version
  type: semver
  source:
    bucket: ci-pcf-workshop-artifacts
    key: lab-current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0

- name: lab-release
  type: s3
  source:
    bucket: ci-pcf-workshop-artifacts
    regexp: contactDataService-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

jobs:
- name: unit-test
  public: true
  plan:
  - get: lab-repo
    trigger: true
  - task: unit-test
    file: lab-repo/lab1/ci/tasks/unit-test.yml
    timeout: 5m

- name: build-binary
  public: true
  serial: true
  plan:
  - get: lab-repo
    passed: [unit-test]
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-artifact
    file: lab-repo/lab1/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: lab-release
    params: {file: build-artifact/contactDataService-*.jar}
  - put: version
    params: {file: version/number}
