spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    io.pivotal.demo: DEBUG
    org.hibernate.SQL: DEBUG
info:
  component: Contact Data Service
  build:
    name: ${project.name:contactDataService}
    description: ${project.description:Event-Driven Contact Data Service using Spring JPA, REST, AMQP}
    version: ${project.version:0.0.1-SNAPSHOT}
    group: ${project.groupId:io.pivotal.demo}
    artifact: ${project.artifactId:contactDataService}

---
spring:
  profiles: local
  datasource:
    platform: h2
  
---
spring:
  profiles: cloud
  datasource:
    platform: mysql